import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '<operationDev>/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

const About = () => {
  return (
    <>
      <Head>
        <title>Operation Dev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
       <h1>AboutAboutAboutAboutAbout</h1>
       <a href='/'>Home</a>
      </main>
    </>
  )
}

export default About;
