import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '<operationDev>/styles/Home.module.css'
import Link from "next/link"
import { getFeaturedEvents } from '../dummy-data'
import EventList from 'components/event-list'




const Home = () => {

  const featureEvents = getFeaturedEvents()

  return (
    <>
      <Head>
        <title>Dummy Events</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
       <EventList items={featureEvents} />
      </main>
    </>
  )
}

export default Home;
