import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "<operationDev>/styles/Home.module.css";
import { useRouter } from "next/router";
import { getEventById } from "../../dummy-data";
import classes from "../../../components/componentsStyles/event-item.module.css";
import ArrowRightIcon from "../../../public/icons/arrow-right-icon";
import DateIcon from "../../../public/icons/date-icon";
import AddressIcon from "../../../public/icons/address-icon";
import Link from "next/link";

const EventDetail = () => {
  //portafolioId
  const router = useRouter();
  const { idEvent } = router.query;
  const event = getEventById(idEvent);
  console.log("event", event);
  if (!event) {
    return <p>Not Found 404</p>;
  }

  const humanReadableDate = new Date(event.date).toLocaleDateString("en-US", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });
  const formattedAddress = event.location.replace(",", "\n");

  return (
    <>
      <Head>
        <title>{event.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="item-detail">
          <Link className="back" href="/">
            <span>Back</span>
          </Link>
          <img src={"/" + event.image} alt={event.image} />

          <div className="item-detail.cont">
            <div className={classes.summary}>
              <h1 className="title">{event.title}</h1>
              <div className="data-cont">
                <div className={classes.date}>
                  <DateIcon />
                  <time>{humanReadableDate}</time>
                </div>
                <div className={classes.address}>
                  <AddressIcon />
                  <address>{formattedAddress}</address>
                </div>
              </div>
              <p className="description">{event.description}</p>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default EventDetail;
